### ISSUE TITLE
Running ./jbxvt just prints RES:FNT

### ISSUE THREAD

**Issue by CamilleScholtz** [jefbed/jbxvt#3]
What does this mean, am I doing something wrong?

**Comment by alisabedard** [comment]
I'll update the error message to be more descriptive.  This error means the font resource could not be loaded.  Either install the terminus fonts or edit config.h and change DEF_FONT and BOLD_FONT to a fixed-width font of your choosing.

**Comment by alisabedard** [comment]
I just updated the font loading code to use a fallback font if the configured font could not be loaded.  Please test.  I also added more descriptive error messages.  By the way, fonts can also be specified on the command line with the -F and -B switches, with -F specifying the normal font, and -B the bold font.

**Comment by CamilleScholtz** [comment]
Yup, works, thanks :)
